---
title: "Engagement Analysis"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
eng <- read_rds("terms.rds") %>% 
  left_join(read_rds("articles.rds")) %>% 
  filter(year < 2019) 
periods <- c("< 2005","2005-2009","2010-2014","2015 <")
disciplines <- c("Marketing","Management","Tourism","Public")
```


## Run a topic model
```{r}
library(topicmodels)

dtm_text <- eng %>%
  filter(research_field=="Marketing") %>% 
  cast_dtm(document, term, count)

lda_out <- dtm_text %>% 
  LDA(
    k = 10, 
    method = "Gibbs",
    control = list(seed = 42)
  )
```

## Visualize probabilities
```{r}

# Topic Word Probabilities
lda_topics <- lda_out %>% 
  tidy(matrix = "beta")

#lda_topics

# Visualize, Name, and Choose K
lda_topics %>%
  group_by(topic) %>% 
  top_n(10, beta) %>% 
  ungroup() %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = as.factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip()

```

## Visualize topics

```{r}
library(gistr)
library(LDAvis)
doc_length <- eng %>%
  filter(research_field=="Marketing") %>% 
  count(document)

term_freq <- eng %>%
  filter(research_field=="Marketing") %>% 
  count(term)

json <- createJSON(
  phi = posterior(lda_out)$terms %>% as.matrix,
  theta = posterior(lda_out)$topics %>% as.matrix,
  vocab <- colnames(posterior(lda_out)$terms %>% as.matrix),
  doc.length = doc_length$n,
  term.frequency = term_freq$n
  )

serVis(json, as.gist = T, description="Engagement Marketing - All Periods", browse=T)
```

